### PR TITLE
scanpy_funcs: Use multi-target regression

### PR DESCRIPTION
**Pull request by ahendriksen**
cuML will gain support for multi-target regression in version 22.12. This speeds up the code significantly since the regression no longer has to be performed inside a for loop. As described in https://github.com/rapidsai/cuml/pull/4988, the speedup can be up to 50x.

This PR adds support for using the multi-target regression. To prevent running out of memory when the input is too large (more than 100000 rows), the existing iterative code path is used.

### CODE REVIEW

**Comment by ahendriksen** [comment]
For a representative use case, this PR speeds up the regression step by a factor of ~20. 

```
import cupy as cp
from cuml.linear_model import LinearRegression
from time import perf_counter as timer
from contextlib import contextmanager

@contextmanager
def bench(name):
    # Code to acquire resource, e.g.:
    start = timer()
    yield
    duration = timer() - start
    print(f"{name}: {duration:0.2f} seconds")

n_cells = 91_000
n_genes = 5_000

normalized = cp.random.normal(size=(n_cells, n_genes))
n_counts = cp.random.normal(size=n_cells)
percent_mito =  cp.random.normal(size=n_cells)

with bench("current regress_out"):
    regress_out(normalized, n_counts, percent_mito, verbose=True) # current

with bench("new regress_out"):
    regress_out(normalized, n_counts, percent_mito, verbose=True) # PR
```

Results on a Volta V100 GPU:
```
Regressed 0 out of 5000
[... snip ...]
Regressed 4500 out of 5000

current regress_out: 16.75 seconds
new regress_out:      0.73 seconds
```

**Comment by Intron7** [comment]
Dear Allard,
great work this works amazingly well.

**Review by cjnolet — CHANGES_REQUESTED** [review]
@ahendriksen this repository hasn't been updated for RAPIDS 22.12 yet. Can you update the environment yaml files in `conda/environment/*.yaml` and the `Dockerfile` and verify the notebooks still run successfully?

**Comment by Intron7** [comment]
So I implement this chunking already for my repo [rapids_singlecell]( https://github.com/Intron7/rapids_singlecell/blob/update-v0.3.1/rapids_singlecell/cunnData_funcs/_regress_out.py) and it works really well. I'm still figuring out the details of the syntax, because its still pretty clunky
I could write something similar for @ahendriksen PR.

**Comment by cjnolet** [comment]
> I could write something similar for @ahendriksen PR.

@Intron7 if you have time to do that, it would certainly be really useful to show off.

**Comment by Intron7** [comment]
@cjnolet @ahendriksen done.

I created a PR for @ahendriksen branch with the batching update.

**Comment by ahendriksen** [comment]
Thank you for adding the batching update @Intron7! 

> @ahendriksen this repository hasn't been updated for RAPIDS 22.12 yet. Can you update the environment yaml files in conda/environment/*.yaml and the Dockerfile and verify the notebooks still run successfully?

I have tested that the code / notebook in this PR runs successfully on RAPIDS 22.12. I have not tested if all other notebooks continue to run successfully.

**Comment by Intron7** [comment]
@ahendriksen @cjnolet Perfect. I think this in a hugh improvement since this was one of the slowest parts of the analysis

**Comment by cjnolet** [comment]
> I have to test tomorrow if we have to change the code for the multigpu notebook to set the batchsize argument there to None. The default is now a batchsize of 100. But i can change that to whatever you want.

@Intron7 were you able to check this? Does it run successfully for you? If so, I'm okay merging this and I can update the conda yaml file in a follow-on PR.

**Comment by Intron7** [comment]
I found one error within the UVM 1million notebook. Its a memory error with cupy and the cubin hash in the `scale` function. The standard scaler function works but is a lot slower. I'll check the multi version but i can not check for speed since our dgx is a bit on the strange side

**Comment by Intron7** [comment]
@cjnolet The Multi_GPU notebook runs perfectly fine with the default of running 100 genes at once during `regress_out`.

**Comment by cjnolet** [comment]
@Intron7 what hardware did you use to test the UVM notebook? I've found that illegal memory error can commonly happen when 1) precision overflow for an indexing type (like using an int for nnz in sparse data) or 2) when the memory is oversubscribed by too much.

**Comment by Intron7** [comment]
@cjnolet I ran it on a node with an 80GB A100 PCIe and on one of the 80GB A100s in the dgx both the same error.

**Comment by cjnolet** [comment]
Thanks for verifying that, @Intron7! I'll try and take a little deeper look as well

**Comment by Intron7** [comment]
> Thanks for verifying that, @Intron7! I'll try and take a little deeper look as well

It could also be our badly setup GPUs. So if this notebooks work on your end I think its us.

**Review by cjnolet — APPROVED** [review]

**Pull request merged**
